# -*- coding: utf-8 -*-

{
    'name': 'Nomin project',
    'version': '1.0',
    'website': 'https://www.odoo.com/page/project-management',
    "author" : 'Chuluunbor',
    'category': 'Nomin project',
    'depends': [
        'project',
        'sale_timesheet',
        # 'nomin_tender',
        'stock', 
        'project_issue',
        'hr_timesheet',
        # 'project_issue_sheet',
    ],
    'description': "",
    'data': [
             'security/security.xml',
             'email_templates/confirmed_email_template.xml',
             'email_templates/email_template_of_ordering.xml',
             'wizard/import_operation.xml',
             'views/investment_breakdown_view.xml',
             'views/project_project_forecast_view.xml',    
             'views/project_view.xml',
             'views/project_category_view.xml',
             'views/project_stage_view.xml',
             'views/project_task_type_view.xml',
             'views/project_task_view.xml',
             'views/control_budget_view.xml',
             'views/project_issue_view.xml',
            #  TODO FIX LATER
            #  'views/contract_management_view.xml',
             'views/program_order_view.xml',
             'views/ordering_sequence.xml',
             'views/labor_cost_settings_view.xml',
             # 'wizard/refuse_reason_order_view.xml',
             'wizard/rate_project_task_view.xml',
             'wizard/create_purchase_requisition_view.xml',
             'wizard/create_project_ticket.xml',
             'wizard/rate_project_view.xml',
             'wizard/project_cancel_view.xml',
             'wizard/create_project_tender_view.xml',
             'wizard/transfer_user.xml',
             'wizard/import_control_budget.xml',
             'wizard/circle_task_view.xml',
             'wizard/assign_project_task_view.xml',
             'wizard/control_budget_cancel.xml',
             'wizard/control_budget_back.xml',
             'wizard/back_to_allocated_view.xml',
            #  TODO FIX LATER
            #  'views/tender_inherit_view.xml',
            #  'views/inherit_purchase_requisition.xml',
             'views/budget_partner_comparison_view.xml',
             'views/budget_partner_comparison_seq.xml',
             'wizard/create_partner_comparison_wizard.xml',
             'wizard/cancel_partner_comparison_wizard_view.xml',
             'wizard/create_contract_view_wizard.xml',
             'wizard/action_vote_view_wizard.xml',
             'wizard/implemented_tasks_view.xml',
             'wizard/sdlc_integration_wizard.xml',
             'wizard/surplus_budgeted_amount_view.xml',
             'reports/task_rating_report_view.xml',
             'reports/report_deadline_task_view.xml',
             'reports/control_budget_status_report_view.xml',
             'reports/project_status_report_view.xml',
             'reports/project_issue_report_view.xml',
             'reports/tarif_task_report_view.xml',
             'reports/report_tarif_task.xml',
             'reports/control_budget_report.xml',
             'reports/report_task_operation.xml',
             'reports/order_request_report_view.xml',
             'reports/order_plan_report_view.xml',
             'reports/budget_partner_comparison_report_view.xml',
             'views/import_task_view.xml',
             'views/project_task_cron_view.xml',
             'security/ir.model.access.csv',
            #  'static/xml/project_gantt_view.xml',              
             'controller/budget_partner_view.xml',     
             ],
    'test': [
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'assets': {
        'web.assets_frontend': [
           'nomin_project/static/src/js/project_gantt_view.js', 
        ],
        'web.assets_qweb': [
                'nomin_project/static/src/xml/project_gantt_view.xml',
        ]
    },
    'icon': '/nomin_project/static/src/img/logo.jpg',
}