# -*- coding: utf-8 -*-
{
    'name': 'Nomin tender website',
    'version': '2.0',
    'website': 'https://www.odoo.com',
    "author" : 'Chuluunbor.B',
    'category': 'Nomin',
    "summary": "Website",
    'data': [
        #'security/ir_ui_view.xml',
        'views/website.xml',
        'views/templates.xml',
        # 'views/assets.xml',
        'views/pages.xml',
        # 'views/tender_account.xml',
        'views/layout.xml',
        'views/content_list.xml',
        'views/web_context_tunnel.xml',
        'views/web_tender_menu.xml', 
        'portal_user_file_view.xml',
        'views/contract_inherit_view.xml',
        # tender views xml templates
        'views/templates/tender/tender_account_edit_template.xml',
        'views/templates/tender/tender_account_template.xml',
        'views/templates/tender/tender_create_documents_template.xml',
        'views/templates/tender/tender_detail_template.xml',
        'views/templates/tender/tender_documents_details_edit_template.xml',
        'views/templates/tender/tender_documents_details_template.xml',
        'views/templates/tender/tender_complete_documentation_template.xml',
        'views/templates/tender/tender_create_my_document_template.xml',
        'views/templates/tender/tender_documents_template.xml',
        'views/templates/tender/tender_documents_thanks_template.xml',
        'views/templates/tender/tender_general_account_tempate.xml',
        'views/templates/tender/tender_guitsetgeh_ajil_template.xml',
        'views/templates/tender/tender_history_template.xml',
        'views/templates/tender/tender_list_template.xml',
        'views/templates/tender/tender_material_completed_template.xml',
        'views/templates/tender/tender_menu_subscribe_template.xml',
        'views/templates/tender/tender_my_account_template.xml',
        'views/templates/tender/tender_my_document_edit_template.xml',
        'views/templates/tender/tender_my_documents_template.xml',
        'views/templates/tender/tender_new_tender_list_template.xml',
        'views/templates/tender/tender_participant_template.xml',
        'views/templates/tender/tender_participation_template.xml',
        'views/templates/tender/tender_result_detail_template.xml',
        'views/templates/tender/tender_result_list_template.xml',
        'views/templates/tender/tender_result_template.xml',
        'views/templates/tender/tender_same_tender_template.xml',
        'views/templates/tender/tender_search_result_template.xml',
        'views/templates/tender/tender_selection_template.xml',
        'views/templates/tender/tender_send_template.xml',
        'views/templates/tender/tender_thanks_template.xml',
        # partner views xml templates
        'views/templates/partner/partner_check_template.xml',
        'views/templates/partner/partner_edit_request_template.xml',
        'views/templates/partner/partner_not_found_template.xml',
        'views/templates/partner/partner_register_exist_template.xml',
        'views/templates/partner/partner_register_template.xml',
        'views/templates/partner/partner_register_thanks_template.xml',
        'views/templates/partner/partner_search_template.xml',
        'security/ir.model.access.csv',
    ],
    'assets':{
        "web.assets_backend":[
        "/nomin_web/static/js/custom.js",
        "/web/static/lib/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js",
        "/nomin_web/static/src/js/survey_result.js",
        # "/nomin_web/static/src/js/upload.js",
        # "/nomin_web/static/src/js/survey.js",
        # "/web/static/lib/nvd3/d3.v3.js",
        # "/web/static/lib/nvd3/nv.d3.js",
        # "/website_slides/static/src/js/slides.js",
        # "/web/static/lib/jquery/jquery.js",
        # "/website_slides/static/src/js/context_tunnel.js",
        "/website_slides/static/src/scss/website_slides.scss",
        ],
        "web.assets_frontend":[
            # "/web/static/lib/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js",
            # "/web/static/lib/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css",
            # "/web/static/lib/daterangepicker/daterangepicker.css",
            # "/web/static/lib/daterangepicker/daterangepicker.js",
            # "/web/static/lib/jquery/jquery.js",
            "/nomin_web/static/css/bootstrap.css",
            "/nomin_web/static/css/nomin.css",
            "/nomin_web/static/css/responsive.css",
            "/nomin_web/static/css/icons.css",
            "/nomin_web/static/css/website.css",
            "/nomin_web/static/js/custom.js",
            "/nomin_web/static/src/js/survey_result.js",
            "/nomin_web/static/src/css/survey_result.css",
            "/website_slides/static/src/scss/website_slides.scss",

        ]
        },
    'depends': [
        'website', 'portal', 'website_slides'
    ],
    'description': """
    """,
    'test': [
        'static/test/context_tunnel.js',
    ],
    'installable': True,
    'auto_install': False,
    'js': ['static/src/js/survey.js','static/src/js/survey_result.js','static/src/js/upload.js'],
    'application': True,
    'icon': '/nomin_web/static/img/bid.png',
}